apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzaGF3YXJyIiwicGFzc3dvcmQiOiJzaGF3YXJEb2NrZXIiLCJlbWFpbCI6ImFobWFkc2hhd2FyMDRAZ21haWwuY29tIiwiYXV0aCI6ImMyaGhkMkZ5Y2pwemFHRjNZWEpFYjJOclpYST0ifX19
kind: Secret
metadata:
  name: docker-registry
  namespace: strawberry
type: kubernetes.io/dockerconfigjson
